# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='neighborhood',
            new_name='neighborhood_name',
        ),
    ]
